import json
d = {
"rot0": "Rotator Cuff Tear: Surgery or Physiotherapy? | İhsan Eren",
"rot1": "What is a rotator cuff tear, and does every tear need surgery? What an MRI finding means and how well physiotherapy works. Six home exercises and videos.",
"rot2": "Rotator cuff tear",
"rot3": "The rotator cuff is made up of the tendons of four muscles that surround the shoulder joint and let you lift and rotate your arm. Tears usually develop with age, through wear and tear, and many cause no symptoms at all. For tears not caused by a fall or a blow, physiotherapy is the first and an effective treatment for most patients.",
"rot4": "Rate of full-thickness rotator cuff tears found among 664 people screened in a village in Japan",
"rot5": "Share of these tears that caused no symptoms at all",
"rot6": "Rate of full-thickness tears over the age of 80; 11% in people in their 50s",
"rot7": "Patients who did not need surgery for 2 years with a physiotherapy programme",
"rot8": "The rotator cuff tendons get thinner and wear with age. Over time, a tear can form through part of the tendon (partial) or through its whole thickness (full-thickness). The supraspinatus tendon, at the top of the shoulder, is the one most often affected. Sometimes a tear is caused by an injury, such as a fall, a dislocated shoulder or suddenly lifting a heavy load.",
"rot9": "Screening studies show that full-thickness tears become much more common with age and that most cause no symptoms. So a tear seen on an MRI does not, on its own, decide your treatment.",
"rot10": "Pain on the outside of the shoulder when you lift your arm out to the side or forwards",
"rot11": "Pain that gets worse at night, especially when you lie on that shoulder",
"rot12": "Weakness when you lift or rotate your arm",
"rot13": "Difficulty brushing your hair, reaching up to a high shelf or reaching behind your back",
"rot14": "Suddenly being unable to lift your arm after an injury",
"rot15": "Surgery or physiotherapy?",
"rot16": "In the MOON study in the US, which followed 452 patients with a full-thickness tear not caused by trauma, about 75% of patients did not need surgery for 2 years after a physiotherapy programme. Those who chose surgery mostly did so within the first 6–12 weeks; after that, few patients went on to have surgery.",
"rot17": "In a study in Finland of patients over 55 with small tears not caused by trauma, physiotherapy gave results as good as surgery at an average follow-up of 6 years; satisfaction was 88–92% in every group. However, another study in Norway, of small and medium-sized tears, found better results after 10 years in the group that had a repair.",
"rot18": "That is why the decision is an individual one. Early orthopaedic assessment is important for tears that start suddenly, such as being unable to lift your arm after a fall or a blow, and for young, active patients. For tears caused by wear, a regular physiotherapy programme is usually tried first.",
"rot19": "Exercises that strengthen the healthy parts of the rotator cuff, the muscles around the shoulder and the shoulder blade muscles, and maintain your range of movement.",
"rot20": "Overhead tasks and heavy lifting that clearly increase your pain are cut back for a while; the arm is not put in a sling, and you keep using it in daily life.",
"rot21": "Cold or heat, and painkillers recommended by your doctor, make it easier to keep exercising.",
"rot22": "Hands-on treatment for the shoulder and upper back, combined with exercise, can help reduce pain and improve movement.",
"rot23": "An orthopaedic specialist assesses the need for surgery for traumatic tears, for young and active patients, and when symptoms do not improve despite regular physiotherapy.",
"rot24": "Do the exercises within a pain-free or mildly painful range; if your pain is no worse the next day, carry on. Start with isometric exercises and move on to light weights as the pain eases.",
"rot25": "Videos for the rotator cuff",
"rot26": "My MRI shows a tear. Should I have surgery?",
"rot27": "Not always. Shoulder tears are common with age, and most tears cause no symptoms. For tears not caused by a fall or a blow, physiotherapy is usually tried first; surgery is considered for tears that do not improve or that were caused by a sudden injury.",
"rot28": "Will the tear heal with physiotherapy?",
"rot29": "A full-thickness tear does not usually close up on its own. But once the healthy parts of the rotator cuff and the shoulder blade muscles get stronger, the shoulder can often become pain-free and work well despite the tear.",
"rot30": "Which side should I sleep on at night?",
"rot31": "Lying on the painful shoulder can make the pain worse. It may help to lie on your good side with your painful arm resting on a pillow in front of you, or to support your arm with a pillow when you lie on your back.",
"rot32": "Can exercise make the tear bigger?",
"rot33": "Controlled exercise, increased gradually, is considered safe and is the foundation of treatment. For a while, cut back on heavy lifting and overhead strain that clearly increase your pain; keep up your exercises as far as the pain allows.",
"rot34": "Being completely unable to lift your arm after a fall or a blow",
"rot35": "A change in the shape of the shoulder, or a suspected dislocation",
"rot36": "Redness or warmth in the shoulder, or a fever",
"rot37": "Numbness, tingling or loss of strength spreading into the arm",
"rot38": "Left shoulder and arm pain together with chest pain, shortness of breath or sweating (call <strong>112</strong>)",
"rot39": "Hello, I would like to book a home assessment and session for a rotator cuff tear.",
}
print(len(d["rot1"]))
json.dump(d, open("i18n/done/rotator-manset-yirtigi.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
