import json
E = {
"Logo tescillidir.":"The logo is a registered trademark.",
"E-posta gönderin":"Send an email",
"Ne yaşadığınızı, neyi yeniden yapabilmek istediğinizi bir mesajla anlatın; size en kısa sürede dönüş yapayım. İstanbul içinde evde fizyoterapi hizmeti.":"Tell me in a message what you’re going through and what you’d like to be able to do again; I’ll get back to you as soon as I can. Home physiotherapy across Istanbul.",
"Hikâyenizi dinleyerek başlayalım.":"Let’s start with your story.",
"Size uygun günü ve saati WhatsApp’tan ya da e-postayla yazabilirsiniz.":"You can send me a day and time that suit you on WhatsApp or by email.",
"Tanışma görüşmesi":"Introductory call",
"Tanışma görüşmesi planla":"Book an introductory call",
"Merhaba, tanışma görüşmesi için {day}, {time} arası bana uygun. Görüşme şekli: {mode}.":"Hello, I’d like to arrange an introductory call. {day}, {time} would suit me. Preferred format: {mode}.",
"E-postayla gönder":"Send by email",
"WhatsApp’tan gönder":"Send on WhatsApp",
"Bir gün ve saat aralığı seçin.":"Choose a day and a time window.",
"Görüntülü":"Video","Telefon":"Phone",
"Görüşme şekli":"Call type",
"<span>3</span>Görüşme şekli":"<span>3</span>Call type",
"Akşam":"Evening","Öğleden sonra":"Afternoon","Öğle":"Midday","Sabah":"Morning",
"Saat aralığı":"Time window",
"<span>2</span>Saat aralığı":"<span>2</span>Time window",
"<span>1</span>Gün":"<span>1</span>Day",
"Gün":"Day",
"Seçtiğiniz zaman bir taleptir; onayladığımda kesinleşir.":"The time you choose is a request; it’s confirmed once I reply.",
"Zaman seçin":"Choose a time",
"Uygunsa ilk ev ziyaretini planlarız":"If it’s a good fit, we plan the first home visit",
"Şikâyetinizi ve hedefinizi birlikte konuşuruz":"We talk through your symptoms and your goals",
"Telefonla ya da görüntülü, kısa bir sohbet":"A short chat, by phone or video",
"Kısa bir ön görüşmede neler yaşadığınızı dinleyeyim, evde nasıl bir yol izleyebileceğimizi birlikte konuşalım. Size uygun günü ve saat aralığını seçin; onaylayıp size dönüş yapayım.":"In a short first conversation I’ll listen to what you’re going through, and we’ll talk about how we could work together at home. Pick a day and a time window that suit you; I’ll confirm and get back to you.",
"Önce tanışalım":"Let’s meet first",
"Değerlendirmeden tedaviye, egzersizden takibe: evde bir sürecin nasıl ilerlediğini anlatmak için hazırlanmış görseller.":"From assessment to treatment, from exercise to follow-up: images prepared to show how care at home unfolds.",
"Evde bir seansın hikâyesi":"The story of a home session",
"Gerçek yaşınız kaç?":"What’s your real age?",
"Örnek rapor: A.Y., 62 yaş. Değerlendirmenin sonunda bütün ölçümler, anlaşılır bir raporda sizinle birlikte gözden geçirilir.":"Sample report: A.Y., aged 62. At the end of the assessment, we go through every measurement together in a clear, easy-to-read report.",
"Sonraki slayt":"Next slide","Otomatik oynatma":"Autoplay","Önceki slayt":"Previous slide",
"Ve en önemlisi: bu yaz torunlarla doğa yürüyüşü.":"And most importantly: nature walks with the grandchildren this summer.",
"Tam analiz":"Full analysis","6. ay":"Month 6","Yeniden ölçüm":"Re-test","3. ay":"Month 3","6. hafta":"Week 6","Bugün":"Today","Başlangıç":"Start","Kontrol":"Check-up",
"Günde 7.000+ adım, günde kilo başına 1,2 g protein":"7,000+ steps and 1.2 g of protein per kilo of body weight a day",
"Günlük yaşam":"Daily life",
"Sol tarafa ek set, kalça ve baldır esnekliği":"Extra sets on the left side; hip and calf flexibility",
"Esneklik ve asimetri":"Flexibility and asymmetry",
"Her gün 5 dakika mobilite ve germe":"5 minutes of mobility and stretching every day",
"Ayak bileği":"Ankle",
"Haftada 3 gün, hızlı kalkış odaklı güç çalışması":"Power training focused on rising quickly, 3 days a week",
"Bacak gücü":"Leg strength",
"Öncelik: bacak gücü ve ayak bileği":"Priority: leg strength and the ankle",
"12 haftalık plan":"12-week plan",
"Her kontrolde aynı testler tekrarlanır; küçük değişimler erkenden fark edilir.":"The same tests are repeated at every check-up, so small changes are spotted early.",
"Tem 26":"Jul 26","Oca 26":"Jan 26","Tem 25":"Jul 25","Oca 25":"Jan 25","Tem 24":"Jul 24","Oca 24":"Jan 24",
"Yürüme hızı (m/sn)":"Walking speed (m/s)",
"24 kg":"24 kg","Eşik 16 kg":"Threshold 16 kg","Kavrama gücü (kg)":"Grip strength (kg)",
"Kavrama gücü toparlanıyor, yürüme hızı takipte":"Grip strength is recovering; walking speed is being watched",
"Zaman içinde izlem":"Tracking over time",
"Otur-kalk":"Sit-to-stand","Yürüme":"Walking","SPPB · fiziksel performans":"SPPB · physical performance",
"Faz açısı":"Phase angle","ASMI · kg/m²":"ASMI · kg/m²","Kas kütlesi":"Muscle mass","Yağ oranı":"Body fat",
"Kas kütlesini korumak öncelikli":"Preserving muscle mass comes first",
"Vücut kompozisyonu ve performans":"Body composition and performance",
"Sağ ile sol arasındaki farkın %10’u aşması denge ve hareket kontrolü açısından dikkate alınır; programda sol tarafa ek set eklenir.":"A gap of more than 10% between right and left matters for balance and movement control, so the programme adds extra sets on the left side.",
"Diz ekstansiyon<em>%8 fark</em>":"Knee extension<em>8% gap</em>",
"Diz fleksiyon<em>%7 fark</em>":"Knee flexion<em>7% gap</em>",
"Kalça abdüksiyon<em>%12 fark</em>":"Hip abduction<em>12% gap</em>",
"Ayak bileği dorsifleksiyon<em>%13 fark</em>":"Ankle dorsiflexion<em>13% gap</em>",
"Kavrama<em>%4 fark</em>":"Grip<em>4% gap</em>",
"Sağ":"Right","Sol":"Left","Yaş normuna göre %":"% of age norm",
"Sol ayak bileği ve kalça biraz geride":"The left ankle and hip lag a little behind",
"Kuvvet asimetrisi":"Strength asymmetry",
"iyi":"good","SPPB":"SPPB","+2 sn":"+2 s","normal":"normal","16 sn":"16 s","Tek ayak durma":"Single-leg stance",
"kısıtlı":"limited","7 cm":"7 cm","Ayak bileği duvar testi":"Ankle knee-to-wall test","1,15 m/sn":"1.15 m/s",
"Yürüme hızı":"Walking speed","hedef":"target","düşük":"low","1,8 W/kg":"1.8 W/kg","Otur-kalk gücü":"Sit-to-stand power",
"−0,9 sn":"−0.9 s","sınırda":"borderline","13,8 sn":"13.8 s","5 kez otur-kalk":"5 sit-to-stands","+1 kg":"+1 kg",
"El sıkma":"Handgrip","Değişim":"Change","Durum":"Status","Test":"Test",
"Yedi test, tek bakışta":"Seven tests at a glance","Ölçümler":"Measurements",
"Denge ve yürüme hızı çok iyi; bacak gücü ve esneklik programın odağında.":"Balance and walking speed are very good; leg strength and flexibility are the focus of the programme.",
"Dayanıklılık":"Endurance","Esneklik":"Flexibility","Kavrama":"Grip","Denge":"Balance",
"Güçlü yanlar ve gelişim alanları":"Strengths and areas to build",
"Yaş normuna göre profil":"Profile against age norms",
"Düşük":"Low","Kırılganlık":"Frailty","Orta":"Moderate","Sarkopeni riski":"Sarcopenia risk","Düşme riski":"Fall risk",
"Takvim yaşı 62":"Calendar age 62","Fonksiyonel yaş 54":"Functional age 54","fonksiyonel yaş":"functional age",
"−8 yıl":"−8 years","Yaşıtlarından 8 yıl önde":"8 years ahead of their peers","Fonksiyonel yaş":"Functional age",
"Bu yaz torunlarımla doğa yürüyüşüne çıkmak istiyorum.":"I want to go on nature walks with my grandchildren this summer.",
"Hedefi:":"Goal:","AY":"AY","A.Y. · 62 yaş":"A.Y. · aged 62","Örnek rapor":"Sample report","Örnek analiz raporu":"Sample analysis report",
}
todo=[]; done={}
for i,(k,v) in enumerate(E.items()):
    kind = "attr" if k in ("Görüşme şekli","Saat aralığı","Sonraki slayt","Otomatik oynatma","Önceki slayt","Örnek analiz raporu","Gün") else "text"
    todo.append({"id":f"fb{i+1}","kind":kind,"tr":k}); done[f"fb{i+1}"]=v
json.dump(todo,open("i18n/todo/fb1.json","w",encoding="utf-8"),ensure_ascii=False,indent=1)
json.dump(done,open("i18n/done/fb1.json","w",encoding="utf-8"),ensure_ascii=False,indent=1)
print(len(E))
