import json
d = {
"sko0": "Scoliosis: Symptoms, Exercises and Brace Treatment | İhsan Eren",
"sko1": "What is scoliosis, how do you spot it at home, and when are exercises, a brace or surgery needed? International guideline advice, a brace study and a home test.",
"sko2": "Scoliosis",
"sko3": "Scoliosis is a sideways curve of the spine that is also twisted around its own axis. It is most common in adolescence, in a type with no known cause (idiopathic), and is usually painless. Because it can progress during periods of rapid growth, it is important to spot it early.",
"sko4": "Last updated: 30 September 2026",
"sko5": "Most commonly reported rate of scoliosis over 10 degrees in adolescents",
"sko6": "Adolescents diagnosed with scoliosis who need exercise or brace treatment; 0.1–0.3% need surgery",
"sko7": "7 to 1",
"sko8": "Ratio of girls to boys among curves over 30 degrees",
"sko9": "Braced adolescents whose curve was kept from reaching the threshold for surgery; 48% in those only monitored",
"sko10": "Scoliosis is when an X-ray shows the spine curving sideways by 10 degrees or more, with rotation of the vertebrae. In about 80% of cases no specific cause is found; this is called idiopathic scoliosis. Small curves are about as common in girls as in boys, but larger curves that progress are much more common in girls.",
"sko11": "The curve progresses most during periods of rapid growth. If the curve has passed a certain threshold by the time growth is complete, the risk of pain and other health problems in adulthood increases.",
"sko12": "How can you spot it?",
"sko13": "One shoulder or one shoulder blade looking higher than the other",
"sko14": "The gaps on either side of the waist looking different",
"sko15": "A bulge on one side of the back when bending forwards (rib hump)",
"sko16": "Clothes, a skirt or trousers hanging to one side",
"sko17": "Adolescent scoliosis is usually painless, so it can easily go unnoticed",
"sko18": "Treatment is planned according to the curve and growth",
"sko19": "According to the guideline of the International Society on Scoliosis Orthopaedic and Rehabilitation Treatment (SOSORT), the aim of treatment is to prevent or limit progression of the curve during growth. The guideline recommends physiotherapeutic scoliosis-specific exercises as the first step in preventing progression and the need for a brace. These exercises are built on three-dimensional self-correction, carrying the corrected posture into daily life, and education, and they should be tailored to each person by physiotherapists trained in these methods.",
"sko20": "In a study of 45 adolescents in Turkey, Schroth exercises done in a clinic with a physiotherapist reduced the curve angle, spinal rotation and rib hump over 24 weeks; in the groups that exercised alone at home or did no exercise, the findings got worse.",
"sko21": "A brace is recommended for adolescents who are still growing and whose curve is greater than 20–25 degrees. In the BrAIST study of 383 adolescents in the US and Canada, the success rate in preventing the curve from reaching 50 degrees, the threshold for surgery, was 72% in those who wore a brace and 48% in those who were only monitored. In those who wore the brace for an average of 13 hours a day or more, success was over 90%.",
"sko22": "Observation",
"sko23": "For small curves, regular check-ups throughout growth, with an X-ray when needed.",
"sko24": "Scoliosis-specific exercises",
"sko25": "A personalised programme based on the type of curve, using methods such as Schroth; the first-line treatment.",
"sko26": "Brace",
"sko27": "For adolescents who are still growing and whose curve is progressing or greater than 20–25 degrees; together with exercises.",
"sko28": "Advanced curves are assessed by an orthopaedic specialist.",
"sko29": "Sport",
"sko30": "Because of its general health and psychological benefits, it should be kept up even during brace treatment; however, on its own it is not a substitute for treatment.",
"sko31": "At home",
"sko32": "A home check and general exercises",
"sko33": "The test on the first card is a simple check you can do at home during the growth years. The other exercises strengthen the trunk muscles and support posture, but they do not correct the curve on their own; scoliosis-specific exercises should be taught individually, based on the type of curve.",
"sko34": "Forward bend test",
"sko35": "Forward bend test (home check)",
"sko36": "Ask your child to bend forwards with feet together and knees straight, letting the arms hang freely. Looking from behind, check whether both sides of the back are at the same height. If there is a clear bulge on one side, see a specialist.",
"sko37": "Every few months during growth",
"sko38": "Lie on your side with your elbow under your shoulder and your knees bent. Lift your hips to make a straight line from your head to your knees, then slowly lower. Your physiotherapist will decide which side you need to work on more.",
"sko39": "Get on your hands and knees. As you breathe out, round your back up towards the ceiling; as you breathe in, slowly let your lower back sink down. Move slowly and stay within a pain-free range.",
"sko40": "Lie on your back with your knees bent and your feet on the floor. Squeeze your buttocks and slowly lift your hips; hold for 3 seconds, then lower.",
"sko41": "Sit or stand up straight. Without lifting your shoulders, draw your shoulder blades back and down towards each other; hold for 5 seconds, then release.",
"sko42": "Can a heavy bag or poor posture cause scoliosis?",
"sko43": "No. The cause of scoliosis in adolescence is unknown; heavy bags or poor posture do not cause it. However, a postural problem that corrects itself when you stand up straight needs to be told apart from true scoliosis.",
"sko44": "Does swimming correct scoliosis?",
"sko45": "No. The international guideline advises that sport should not be recommended as a treatment for scoliosis, but that it should not be given up either, because of its general health and psychological benefits. No sport, including swimming, corrects the curve on its own.",
"sko46": "Can exercise cure scoliosis completely?",
"sko47": "In small curves, scoliosis-specific exercises can help prevent progression and, in some patients, reduce the angle by a few degrees; however, they are not expected to get rid of the curve completely. Which treatment is needed is decided by looking at the curve angle and growth status together.",
"sko48": "How long should a brace be worn?",
"sko49": "How well a brace works depends on how long it is worn. In the BrAIST study, the success rate was over 90% in those who wore the brace for an average of 13 hours a day or more; in those who wore it for less than 6 hours, the results were no different from those who did not wear a brace. Your doctor will decide how long it should be worn.",
"sko50": "Marked back pain, or back pain that wakes you at night (adolescent scoliosis is usually painless)",
"sko51": "Numbness or weakness in the arms or legs, or difficulty walking; problems with bladder or bowel control",
"sko52": "A noticeable increase in the curve or hump over a short time",
"sko53": "A curve noticed before the age of 10",
"sko54": "Shortness of breath",
"sko55": "If you would like to book a comprehensive functional assessment at home and a personalised rehabilitation session for scoliosis, get in touch on WhatsApp.",
"sko56": "Hello, I would like to book a home assessment and session for scoliosis.",
"sko57": "Kuru T, Yeldan I, Dereli EE, et al. <a href=\"https://journals.sagepub.com/doi/abs/10.1177/0269215515575745\" target=\"_blank\" rel=\"noopener\">The efficacy of three-dimensional Schroth exercises in adolescent idiopathic scoliosis: a randomised controlled clinical trial</a>. Clin Rehabil. 2016;30(2):181-190.",
}
json.dump(d, open("i18n/done/skolyoz.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(len(d), len(d["sko1"]))
